delete from [dbo].[AccuHealthParamMappings]
go
truncate table [dbo].[AccuHealthParamMappings]
GO
delete from [dbo].[EquipmentMaster]
GO
SET IDENTITY_INSERT [dbo].[EquipmentMaster] ON 
go
insert into [dbo].[EquipmentMaster](Id,Name,Model,AccessKey,IsActive,CreatedBy,CreatedOn)
values 
(1,'BC30A','BC30A','ACCU-HEALTH-BC30A-1',1,'admin@zorya.co.in',getdate()),
(2,'BS400','BS400','ACCU-HEALTH-BS400-1',1,'admin@zorya.co.in',getdate()),
(3,'CL1200','CL1200','ACCU-HEALTH-CL1200-1',1,'admin@zorya.co.in',getdate()),
(4,'EC90','EC90','ACCU-HEALTH-EC90-1',1,'admin@zorya.co.in',getdate()),
(5,'EM200','EM200','ACCU-HEALTH-EM200-1',1,'admin@zorya.co.in',getdate()),
(6,'ERBAH560','ERBAH560','ACCU-HEALTH-ERBAH560-1',1,'admin@zorya.co.in',getdate()),
(7,'MINIVIDAS','MINIVIDAS','ACCU-HEALTH-MINIVIDAS-1',1,'admin@zorya.co.in',getdate()),
(8,'SYSMEXXN330','SYSMEXXN330','ACCU-HEALTH-SYSMEXXN330-1',1,'admin@zorya.co.in',getdate()),
(9,'ZYBIO','ZYBIO','ACCU-HEALTH-ZYBIO-1',1,'admin@zorya.co.in',getdate())
go
SET IDENTITY_INSERT [dbo].[EquipmentMaster] OFF
GO
insert into [dbo].[AccuHealthParamMappings] (HIS_PARAMCODE,LIS_PARAMCODE,HIS_PARAMNAME,EquipmentId)
values
('Hematocrit (PCV) ','HCT','Hematocrit (PCV) ',1),
('MCH','MCH','MCH',1),
('MCHC','MCHC','MCHC',1),
('MCV','MCV','MCV',1),
('PLATELET COUNT','PLT','PLATELET COUNT',1),
('RBC','RBC','RBC',1),
('RBC COUNT','RBC','RBC COUNT',1),
('Total Leucocyte Count(correct value)','WBC','Total Leucocyte Count(correct value)',1),
('Total Leucocyte Count','WBC','Total Leucocyte Count',1),
('RDW','RDW-CV','RDW',1),
('PCV','HCT','PCV',1),
('Haemoglobin','HGB','Haemoglobin',1),
('Bilirubin Conjugated','1','Bilirubin Conjugated',2),
('Bilirubin Total','2','Bilirubin Total',2),
('AMYLASE','3','AMYLASE',2),
('AMYLASE','a-AMY','AMYLASE',2),
('SERUM AMYLASE','a-AMY','SERUM AMYLASE',2),
('ANTI CCP','A-CCP','ANTI CCP',2),
('A-CCP','A-CCP','A-CCP',2),
('ANTI CCP','ACCP-O','ANTI CCP',2),
('ADA (BODY FLUID)','ADA-O','ADA (BODY FLUID)',2),
('ADA(Body Fluid)','ADA-O','ADA(Body Fluid)',2),
('ADA (FLUID)','ADA-O','ADA (FLUID)',2),
('Albumin','ALB II','Albumin',2),
('ALBUMIN (BLOOD)','ALB II','ALBUMIN (BLOOD)',2),
('Alkaline Phosphatase','ALP','Alkaline Phosphatase',2),
('SGPT (ALT)','ALT','SGPT (ALT)',2),
('SGPT','ALT','SGPT',2),
('ALT (SGPT)','ALT','ALT (SGPT)',2),
('ASO TITRE','ASO-O','ASO TITRE',2),
('SGOT','AST','SGOT',2),
('SGOT (AST)','AST','SGOT (AST)',2),
('AST (SGOT)','AST','AST (SGOT)',2),
('CALCIUM','Ca','CALCIUM',2),
('CREATININE','CRE-Z','CREATININE',2),
('Serum Creatinine','CRE-Z','Serum Creatinine',2),
('CRP - C REACTIVE PROTEIN','CRP II','CRP - C REACTIVE PROTEIN',2),
('CRP','CRP II','CRP',2),
('Bilirubin Conjugated','D-bil-D II','Bilirubin Conjugated',2),
('GLOBULIN','Glo','GLOBULIN',2),
('GLUCOSE FASTING','GLU','GLUCOSE FASTING',2),
('GLUCOSE RANDOM','GLU','GLUCOSE RANDOM',2),
('GLUCOSE PP','GLU','GLUCOSE PP',2),
('HDL Cholesterol','HDL-C','HDL Cholesterol',2),
('Total IgE','IGE','Total IgE',2),
('IMMUNOGLOBULIN IGE','IGE','IMMUNOGLOBULIN IGE',2),
('LDH TOTAL','LDH','LDH TOTAL',2),
('LDL Cholesterol','LDL-C','LDL Cholesterol',2),
('LIPASE','LIP','LIPASE',2),
('MICROALBUMIN / CREATININE RATIO','MALB-O','MICROALBUMIN / CREATININE RATIO',2),
('Microalbumin & Creatinine Ratio','MALB-O','Microalbumin & Creatinine Ratio',2),
('Microalbumin and Creatinine Ratio','MALB-O','Microalbumin and Creatinine Ratio',2),
('SERUM INORGANIC PHOSPHORUS (PO4)','P','SERUM INORGANIC PHOSPHORUS (PO4)',2),
('RHEUMATOID FACTOR','RF','RHEUMATOID FACTOR',2),
('Bilirubin Total','T-bil-D II','Bilirubin Total',2),
('Cholesterol','TC','Cholesterol',2),
('TRIGLYCERIDE','TG','TRIGLYCERIDE',2),
('Triglycerides','TG','Triglycerides',2),
('Total Protein','TP','Total Protein',2),
('Uric Acid','UA','Uric Acid',2),
('UREA','UREA','UREA',2),
('GGT','y-GT','GGT',2),
('GGT - GAMMA GLUTAMYL TRANSFERASE','y-GT','GGT - GAMMA GLUTAMYL TRANSFERASE',2),
('A-CCP','ACCP-O','A-CCP',2),
('ALPHA FETOPROTEIN (AFP)','AFP','ALPHA FETOPROTEIN (AFP)',3),
('AMH - ANTI MULLERIAN HORMONE','AMH','AMH - ANTI MULLERIAN HORMONE',3),
('AMH (ANTI-MULLERIAN HORMONE)','AMH','AMH (ANTI-MULLERIAN HORMONE)',3),
('ANTI TPO ANTIBODY','Anti-TPO','ANTI TPO ANTIBODY',3),
('PRO BNP','BNP','PRO BNP',3),
('C-PEPTIDE','C-Peptide','C-PEPTIDE',3),
('CA 125','CA125','CA 125',3),
('CA 15.3','CA15','CA 15.3',3),
('CA 19.9','CA19','CA 19.9',3),
('CEA','CEA','CEA',3),
('CORTISOL (PM)','Cortisol','CORTISOL (PM)',3),
('CORTISOL (AM)','Cortisol','CORTISOL (AM)',3),
('DHEA','DHEA-S','DHEA',3),
('E2 - ESTRADIOL','E2','E2 - ESTRADIOL',3),
('FERRITIN','FERR','FERRITIN',3),
('FOLIC ACID','Folate','FOLIC ACID',3),
('FREE PSA - PROSTATE SPECIFIC ANTIGEN FREE','FPSA','FREE PSA - PROSTATE SPECIFIC ANTIGEN FREE',3),
('FSH ','FSH','FSH ',3),
('FT3 - FREE TRIIODOTHYRONINE','FT3','FT3 - FREE TRIIODOTHYRONINE',3),
('FREE T3','FT3','FREE T3',3),
('FREE T4','FT4','FREE T4',3),
('FT4 - FREE THYROXINE','FT4','FT4 - FREE THYROXINE',3),
('BETA HCG','HCG','BETA HCG',3),
('BETA HCG(SERUM)','HCG','BETA HCG(SERUM)',3),
('INSULIN (FASTING)','Insulin','INSULIN (FASTING)',3),
('INSULIN ASSAY ( FASTING ) ','Insulin','INSULIN ASSAY ( FASTING ) ',3),
('INSULIN(PP)','Insulin','INSULIN(PP)',3),
('LH','LH','LH',3),
('PROCALCITONIN','PCT','PROCALCITONIN',3),
('PROLACTIN','PRL','PROLACTIN',3),
('PSA','PSA','PSA',3),
('PTH - PARATHYROID HORMONE INTACT','PTH','PTH - PARATHYROID HORMONE INTACT',3),
('T3','T3','T3',3),
('T4','T4','T4',3),
('TESTOSTERONE (TOTAL)','TESTO','TESTOSTERONE (TOTAL)',3),
('BETA HCG','Total ßHCG','BETA HCG',3),
('TSH','TSH','TSH',3),
('Vitamin B-12','VB12','Vitamin B-12',3),
('VITAMIN B12','VB12','VITAMIN B12',3),
('VITAMIN D (25OH)','VD','VITAMIN D (25OH)',3),
('VITAMIN D TOTAL(25 O H)','VD','VITAMIN D TOTAL(25 O H)',3),
('Vitamin D Total (25 O H)','VD','Vitamin D Total (25 O H)',3),
('BETA HCG(SERUM)','Total ßHCG','BETA HCG(SERUM)',3),
('Sodium','Na','Sodium',4),
('Potassium2','K','Potassium2',4),
('Potassium','K','Potassium',4),
('Chloride','Cl','Chloride',4),
('Albumin','ALBD','Albumin',5),
('Alkaline Phosphatase','ALPU','Alkaline Phosphatase',5),
('AMYLASE','AMY','AMYLASE',5),
('BILIRUBIN CONJUGATED','BIDD','BILIRUBIN CONJUGATED',5),
('Bilirubin Total','BIT','Bilirubin Total',5),
('CALCIUM','CA','CALCIUM',5),
('CHOLESTEROL','CHOL','CHOLESTEROL',5),
('CREATININE','CRENZ','CREATININE',5),
('CRP','CRPD','CRP',5),
('GGT','GGT','GGT',5),
('GGT - GAMMA GLUTAMYL TRANSFERASE','GGT','GGT - GAMMA GLUTAMYL TRANSFERASE',5),
('Glucose Fasting','GLU','Glucose Fasting',5),
('GLUCOSE FASTING','GLU','GLUCOSE FASTING',5),
('Glucose pp','GLU','Glucose pp',5),
('GLUCOSE PP','GLU','GLUCOSE PP',5),
('GLUCOSE RANDOM','GLU','GLUCOSE RANDOM',5),
('HDL CHOLESTEROL','HDLC','HDL CHOLESTEROL',5),
('LDH (CSF)','LDH','LDH (CSF)',5),
('LDH (FLUID)','LDH','LDH (FLUID)',5),
('LDH TOTAL','LDH','LDH TOTAL',5),
('LDL Cholesterol','LDL','LDL Cholesterol',5),
('LIPASE','LIP','LIPASE',5),
('PHOPHATE','PHOS','PHOPHATE',5),
('Phosphate','PHOS','Phosphate',5),
('Total Protein','PRO','Total Protein',5),
('RH FACTOR','RFD','RH FACTOR',5),
('RHEUMATOID FACTOR','RFD','RHEUMATOID FACTOR',5),
('SGOT','SGOTD','SGOT',5),
('SGOT (AST)','SGOTD','SGOT (AST)',5),
('SGPT','SGPTD','SGPT',5),
('SGPT (ALT)','SGPTD','SGPT (ALT)',5),
('SGPT(ALT)','SGPTD','SGPT(ALT)',5),
('TRIGLYCERIDE','TRIG','TRIGLYCERIDE',5),
('Triglycerides','TRIG','Triglycerides',5),
('Uric Acid','UA','Uric Acid',5),
('UREA','UREA','UREA',5),
('Glucose PP ( 75gm Glucose)','GLU','Glucose PP ( 75gm Glucose)',5),
('PCV','HCT','PCV',6),
('LYMPHOCYTES','LYM%','LYMPHOCYTES',6),
('MCH','MCH','MCH',6),
('MCHC','MCHC','MCHC',6),
('MCV','MCV','MCV',6),
('PLATELET COUNT','PLT','PLATELET COUNT',6),
('Total Leucocyte Count','WBC','Total Leucocyte Count',6),
('RBC','RBC','RBC',6),
('RBC COUNT','RBC','RBC COUNT',6),
('NEUTROPHILS','GRAN%','NEUTROPHILS',6),
('MCH','MCH','MCH',6),
('MCHC','MCHC','MCHC',6),
('PLATELET COUNT','PLT','PLATELET COUNT',6),
('MCV','MCV','MCV',6),
('RDW','RDW-CV','RDW',6),
('HEMATOCRIT (PCV)','HCT','HEMATOCRIT (PCV)',6),
('NEUTROPHILS','GRAN%','NEUTROPHILS',6),
('RDW','RDW-CV','RDW',6),
('Haemoglobin','HGB','Haemoglobin',6),
('Haemoglobin','HGB','Haemoglobin',6),
('PCV','HCT','PCV',6),
('LYMPHOCYTES','LYM%','LYMPHOCYTES',6),
('Total Leucocyte Count','WBC','Total Leucocyte Count',6),
('RBC','RBC','RBC',6),
('RBC COUNT','RBC','RBC COUNT',6),
('CA 125','125','CA 125',7),
('CA 19.9','199','CA 19.9',7),
('FERRITIN','FER','FERRITIN',7),
('FSH ','FSH','FSH ',7),
('FSH - FOLLICLE STIMULATING HORMONE','FSH','FSH - FOLLICLE STIMULATING HORMONE',7),
('Total IgE','IGE','Total IgE',7),
('LH','LH','LH',7),
('LH - LUTEINIZING HORMONE','LH','LH - LUTEINIZING HORMONE',7),
('TOTAL T3','T3','TOTAL T3',7),
('Triiodothyronine - T3','T3','Triiodothyronine - T3',7),
('T3','T3','T3',7),
('T3 - TOTAL TRIIODOTHYRONINE','T3','T3 - TOTAL TRIIODOTHYRONINE',7),
('T4','T4','T4',7),
('T4 - TOTAL THYROXINE','T4','T4 - TOTAL THYROXINE',7),
('TOTAL T4','T4','TOTAL T4',7),
('PSA TOTAL','TPSA','PSA TOTAL',7),
('PSA','TPSA','PSA',7),
('PSA - PROSTATE SPECIFIC ANTIGEN','TPSA','PSA - PROSTATE SPECIFIC ANTIGEN',7),
('PSA- Prostate Specific Antigen','TPSA','PSA- Prostate Specific Antigen',7),
('TSH','TSH','TSH',7),
('TSH - THYROID-STIMULATING HORMONE','TSH','TSH - THYROID-STIMULATING HORMONE',7),
('FREE T4','FT4N','FREE T4',7),
('FT4 - FREE THYROXINE','FT4N','FT4 - FREE THYROXINE',7),
('VITAMIN D (25OH)','VITD','VITAMIN D (25OH)',7),
('Vitamin D Total (25 O H)','VITD','Vitamin D Total (25 O H)',7),
('vitamin d total (25 oh)','VITD','vitamin d total (25 oh)',7),
('VITAMIN D TOTAL(25 O H)','VITD','VITAMIN D TOTAL(25 O H)',7),
('BASOPHIL','BASO%','BASOPHIL',8),
('Basophils','BASO%','Basophils',8),
('Eosinophil','EO%','Eosinophil',8),
('Eosinophils','EO%','Eosinophils',8),
('PCV','HCT','PCV',8),
('Haemoglobin','HGB','Haemoglobin',8),
('Hb','HGB','Hb',8),
('Hb - HAEMOGLOBIN','HGB','Hb - HAEMOGLOBIN',8),
('Lymphocyte','LYMPH%','Lymphocyte',8),
('Lymphocytes','LYMPH%','Lymphocytes',8),
('MCH','MCH','MCH',8),
('MCHC','MCHC','MCHC',8),
('MCV','MCV','MCV',8),
('Monocyte','MONO%','Monocyte',8),
('Monocytes','MONO%','Monocytes',8),
('Neutrophil ','NEUT%','Neutrophil ',8),
('Neutrophils','NEUT%','Neutrophils',8),
('PLATELET COUNT','PLT','PLATELET COUNT',8),
('RBC','RBC','RBC',8),
('RBC COUNT','RBC','RBC COUNT',8),
('RDW','RDW-CV','RDW',8),
('Total Leucocyte Count','WBC','Total Leucocyte Count',8),
('Hematocrit (PCV) ','HCT','Hematocrit (PCV) ',8),
('Hb','HGB','Hb',9),
('PLATELET COUNT','PLT','PLATELET COUNT',9),
('Hematocrit (PCV) ','HCT','Hematocrit (PCV) ',9),
('Haemoglobin','HGB','Haemoglobin',9),
('Total Leucocyte Count','WBC','Total Leucocyte Count',9),
('Lymphocytes','LYM%','Lymphocytes',9),
('RBC','RBC','RBC',9),
('Neutrophil ','NEU%','Neutrophil ',9),
('MCH','MCH','MCH',9),
('Monocytes','MON%','Monocytes',9),
('Monocyte','MON%','Monocyte',9),
('PCV','HCT','PCV',9),
('RDW','RDW-CV','RDW',9),
('Neutrophils','NEU%','Neutrophils',9),
('Eosinophil','EOS%','Eosinophil',9),
('MCHC','MCHC','MCHC',9),
('Lymphocyte','LYM%','Lymphocyte',9),
('Basophils','BAS%','Basophils',9),
('RBC COUNT','RBC','RBC COUNT',9),
('Eosinophils','EOS%','Eosinophils',9),
('BASOPHIL','BAS%','BASOPHIL',9),
('MCV','MCV','MCV',9),
('Hb - HAEMOGLOBIN','HGB','Hb - HAEMOGLOBIN',9)
go

select * from [dbo].[EquipmentMaster]

select * from [dbo].[AccuHealthParamMappings]






