//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lis.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lis.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits must be evenly divisible by 8..
        /// </summary>
        internal static string AUTH_GENERATOR_MESSAGE {
            get {
                return ResourceManager.GetString("AUTH_GENERATOR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login is already associated with an account..
        /// </summary>
        internal static string AUTH_GENERATOR_PARAM {
            get {
                return ResourceManager.GetString("AUTH_GENERATOR_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item could not be deleted..
        /// </summary>
        internal static string BUSINESS_DELETE {
            get {
                return ResourceManager.GetString("BUSINESS_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call completed successfully.
        /// </summary>
        internal static string CALL_SUCCESS {
            get {
                return ResourceManager.GetString("CALL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not sent..
        /// </summary>
        internal static string CHANGEPASSWORD_MAIL_FAILURE {
            get {
                return ResourceManager.GetString("CHANGEPASSWORD_MAIL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully.
        /// </summary>
        internal static string CHANGEPASSWORD_MAIL_SUCCESS {
            get {
                return ResourceManager.GetString("CHANGEPASSWORD_MAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data..
        /// </summary>
        internal static string CSV_DATA {
            get {
                return ResourceManager.GetString("CSV_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully..
        /// </summary>
        internal static string DATASAVE_SUCCESS {
            get {
                return ResourceManager.GetString("DATASAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully..
        /// </summary>
        internal static string DATAUPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("DATAUPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;To Date&apos; should be greater than &apos;From Date&apos;..
        /// </summary>
        internal static string DATE_COMPARE {
            get {
                return ResourceManager.GetString("DATE_COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        internal static string EXECUTION_FAILURE {
            get {
                return ResourceManager.GetString("EXECUTION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password mail is sent to your registered email address..
        /// </summary>
        internal static string FORGETPASSWORD_MAIL {
            get {
                return ResourceManager.GetString("FORGETPASSWORD_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found..
        /// </summary>
        internal static string FORGETPASSWORD_MAIL_NOTFOUND {
            get {
                return ResourceManager.GetString("FORGETPASSWORD_MAIL_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credential provided..
        /// </summary>
        internal static string INVALID_CREDENTIAL {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login failure..
        /// </summary>
        internal static string LOGIN_FAILURE {
            get {
                return ResourceManager.GetString("LOGIN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login is already associated with an account..
        /// </summary>
        internal static string LOGINASSOCIATED_ACCOUNT {
            get {
                return ResourceManager.GetString("LOGINASSOCIATED_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was not successful.
        /// </summary>
        internal static string PASSWORDCHANGE_FAILURE {
            get {
                return ResourceManager.GetString("PASSWORDCHANGE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        internal static string PASSWORDCHANGE_SUCCESS {
            get {
                return ResourceManager.GetString("PASSWORDCHANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password link has been sent to.
        /// </summary>
        internal static string RESETPASSWORD_MAIL {
            get {
                return ResourceManager.GetString("RESETPASSWORD_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password need to be reset. Please reset your password by clicking.
        /// </summary>
        internal static string RESETPASSWORD_POST {
            get {
                return ResourceManager.GetString("RESETPASSWORD_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        internal static string SEARCH_NOTFOUND {
            get {
                return ResourceManager.GetString("SEARCH_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        internal static string USERCREATION_SUCCESS {
            get {
                return ResourceManager.GetString("USERCREATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the user?.
        /// </summary>
        internal static string USERDELETION_CONFIRM {
            get {
                return ResourceManager.GetString("USERDELETION_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile deleted successfully..
        /// </summary>
        internal static string USERDELETION_SUCCESS {
            get {
                return ResourceManager.GetString("USERDELETION_SUCCESS", resourceCulture);
            }
        }
    }
}
