// <auto-generated />
namespace LIS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class GroupName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GroupName));
        
        string IMigrationMetadata.Id
        {
            get { return "202109170946437_GroupName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
