// <auto-generated />
namespace Lis.Api.DataContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cnci1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cnci1));
        
        string IMigrationMetadata.Id
        {
            get { return "202102040722092_cnci1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
